apiVersion: v1
kind: Pod
metadata:
  name: multi-cont-pod
spec:
  containers:
  - name: first-cont
    image: nginx
  - name: second-cont
    image: tomcat:8
  - name: third-cont
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: my-secret-pw
